const resume =
  "Nikhil Pandey\nEmail: nikhilpandey@gmail.com\nPhone: +91 9876543210\n\nEDUCATION\nBachelor of Science in Computer Science\nXYZ College, Mumbai\nExpected Graduation: 2027\nCGPA: 8.4/10\n\nTECHNICAL SKILLS\n- JavaScript\n- React.js\n- Node.js\n- Express.js\n- MongoDB\n- SQL\n- HTML5\n- CSS3\n- Git & GitHub\n\nPROJECTS\n\n1. AI Mock Interview Platform\n- Built a web application that generates interview questions using AI.\n- Implemented authentication using JWT.\n- Created dashboards for interview reports.\n- Tech Stack: React, Node.js, MongoDB.\n\n2. Student Notes Sharing Platform\n- Developed a subscription-based platform for students.\n- Users can access notes based on selected plans.\n- Tech Stack: React, Express, MongoDB.\n\n3. Restaurant QR Menu System\n- Created a QR-based digital menu system.\n- Customers can scan QR codes to view menus.\n- Tech Stack: JavaScript, Node.js, MongoDB.\n\nEXPERIENCE\n- Freelance Frontend Developer (6 months)\n- Developed responsive websites for local businesses.\n\nACHIEVEMENTS\n- Solved 250+ coding problems on LeetCode.\n- Participated in college hackathons.\n\nSOFT SKILLS\n- Communication\n- Teamwork\n- Problem Solving\n- Adaptability";

const selfDescription =
  "I am a Computer Science student passionate about full-stack web development and artificial intelligence. I enjoy building practical applications that solve real-world problems. I am comfortable working with JavaScript, React, Node.js, and MongoDB. I have experience building personal projects and continuously improving my problem-solving skills through coding challenges. While I am confident in frontend development, I want to strengthen my backend architecture, system design, and data structures knowledge. I am eager to learn, work in teams, and contribute to impactful products.";

const jobDescription =
  "We are looking for a Junior Full Stack Developer to join our engineering team. The candidate should have experience with React.js, Node.js, Express.js, MongoDB, REST APIs, and Git. Knowledge of SQL databases, authentication systems, and cloud deployment is preferred. Candidates should possess strong problem-solving skills, understanding of data structures and algorithms, and the ability to work collaboratively in an agile environment. Experience with testing, performance optimization, and scalable application design is a plus.";

module.exports = { resume, selfDescription, jobDescription };
